### ISSUE TITLE
Any Chance OF This Mod Launcher in English?

### ISSUE THREAD

**Issue by bitsbb01** [forcecore/ZHModLauncher#10]
Any Chance OF This Mod Launcher in English?
Would love to be able to use it

**Comment by forcecore** [comment]
You have 99% chance.

Theoretically, the translation task is an easy one as there's a string table for that job:
https://github.com/forcecore/ZHModLauncher/blob/master/po/mod4.en.po

I didn't know this tool was known outside red2.net, interesting!

**Comment by bitsbb01** [comment]
Yes on CNCz forums, and a few other forums and websites, the problem the found is the language barrier.. 
I do love the mods on red2.net, and as got google translator running for there, its easy to get arround..

**Comment by bitsbb01** [comment]
so i hadnt ever worked with Lazarus, but managed to create the english version for you.. heres the compiled English version.. https://github.com/bitsbb01/storage/raw/main/Mod4.rar

**Comment by bitsbb01** [comment]
So not sure whats going on, but the english version doesnt copy the big to the zh folder. so the mod doesnt activate... 
I also tested your version, and its also not copying the file across and doesnt activate the mod..

**Comment by forcecore** [comment]
> So not sure whats going on, but the english version doesnt copy the big to the zh folder. so the mod doesnt activate... I also tested your version, and its also not copying the file across and doesnt activate the mod..

OK, I'll take a look this weekend.

**Comment by bitsbb01** [comment]
thanks

**Comment by forcecore** [comment]
90ab09827d18a72f1147e1406c70abd90687ad34 should have solved the issue,

The release is here: https://github.com/forcecore/ZHModLauncher/releases/tag/v013
